commonFileTypes = {
    "jpg": "Images",
    "jpeg": "Images",
    "png": "Images",
    "gif": "Images",
    "bmp": "Images",
    "ico": "Images",
    "svg": "Images",
    "webp": "Images",
    "tif": "Images",
    "tiff": "Images",
    "eps": "Images",
    "ai": "Images",
    "psd": "Images",
    "exe": "Executable",
    "msi": "Executable",
    "bat": "Executable",
    "cmd": "Executable",
    "ps1": "Executable",
    "vbs": "Executable",
    "dll": "Dynamic Link Library",
    "sys": "System File",
    "ttf": "Fonts",
    "otf": "Fonts",
    "zip": "Archives",
    "rar": "Archives",
    "7z": "Archives",
    "cab": "Archives",
    "gz": "Archives",
    "tar": "Archives",
    "zipx": "Archives",
    "pdf": "Documents",
    "doc": "Documents",
    "docx": "Documents",
    "txt": "Documents",
    "rtf": "Documents",
    "xls": "Documents",
    "xlsx": "Documents",
    "ppt": "Documents",
    "pptx": "Documents",
    "csv": "Documents",
    "mp3": "Audio",
    "wav": "Audio",
    "ogg": "Audio",
    "flac": "Audio",
    "aac": "Audio",
    "mp4": "Video",
    "avi": "Video",
    "wmv": "Video",
    "mov": "Video",
    "mpg": "Video",
    "mpeg": "Video",
    "lnk": "Shortcut",
    "ini": "Configuration",
    "cfg": "Configuration",
    "log": "Log Files",
    "reg": "Registry Entries",
    "iso": "Disk Image",
    "img": "Disk Image",
    "vhd": "Virtual Hard Disk",
    "csv": "Data",
    "json": "Data",
    "xml": "Data",
    "html": "Web",
    "htm": "Web",
    "css": "Web",
    "js": "Web",
    "php": "Web",
    "asp": "Web",
    "py": "Scripts",
    "bat": "Scripts",
    "ps1": "Scripts",
    "sh": "Scripts",
    "sql": "Database",
    "db": "Database",
    "mdb": "Database",
    "accdb": "Database",
    "csv": "Spreadsheets",
    "xml": "Spreadsheets",
    "xlr": "Spreadsheets",
    "msg": "Emails",
    "eml": "Emails",
    "vcf": "Contacts",
    "ics": "Calendar",
    "bak": "Backup",
    "tmp": "Temporary",
}
